# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v2
      # 使用Docker官方制作的action
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and Push Docker Iamge
        uses: docker/build-push-action@v1
        with: 
          username: codereporter
          password: z19951012tx
          repository: username/repository
          tag_with_sha: true
          path: 'docker'
